# Generated by Django 3.2 on 2021-04-17 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('sender_id', models.TextField(max_length=20, verbose_name='发送者编号')),
                ('reciever_id', models.TextField(max_length=20, verbose_name='接收者编号')),
                ('theme', models.TextField(max_length=50, verbose_name='主题')),
                ('text', models.TextField(max_length=1000, verbose_name='私信内容')),
                ('read_flag', models.BooleanField(default=False, verbose_name='新信息？')),
                ('sender_delete', models.BooleanField(default=False, verbose_name='发送者有将他删除吗')),
                ('reciever_delete', models.BooleanField(default=False, verbose_name='接收者有将他删除吗')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信',
                'db_table': 'MessageInfo',
            },
        ),
    ]
