# Generated by Django 3.2 on 2021-04-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='班级编号')),
                ('name', models.TextField(max_length=100, verbose_name='班级名称')),
                ('people_nums', models.IntegerField(default=0, verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'class',
                'ordering': ['ID'],
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='院系编号')),
                ('name', models.TextField(max_length=100, verbose_name='院系名称')),
                ('name_leader', models.TextField(max_length=100, verbose_name='院长名字')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
                'db_table': 'Departments',
                'ordering': ['ID'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师编号')),
                ('name', models.TextField(max_length=100, verbose_name='教师名称')),
                ('job', models.TextField(max_length=100, verbose_name='职位')),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departments')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
                'ordering': ['ID'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师编号')),
                ('name', models.TextField(max_length=100, verbose_name='学生姓名')),
                ('ofclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.class')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'ordering': ['ID'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.departments'),
        ),
    ]
