# Generated by Django 3.2 on 2021-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.TextField(default=' ', max_length=500, verbose_name='所学课程'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.TextField(default=' ', max_length=500, verbose_name='所教课程'),
        ),
    ]
