# Generated by Django 3.2 on 2021-04-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.TextField(max_length=20, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.TextField(max_length=20, verbose_name='院系名称'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_leader',
            field=models.TextField(max_length=10, verbose_name='院长名字'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=20, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job',
            field=models.TextField(max_length=10, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.TextField(max_length=20, verbose_name='教师名称'),
        ),
    ]
