# Generated by Django 3.2 on 2021-04-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210415_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='用户姓名')),
                ('state', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1)),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sourse_num', models.IntegerField(default=0, verbose_name='已经上传的资源数')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'userTeacher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='用户姓名')),
                ('state', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=1)),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sourse_num', models.IntegerField(default=0, verbose_name='已经上传的资源数')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'userStudent',
                'ordering': ['name'],
            },
        ),
    ]
