# Generated by Django 3.2 on 2021-04-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userstudent_userteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='name',
            field=models.TextField(max_length=20, unique=True, verbose_name='用户姓名'),
        ),
    ]
