# Generated by Django 3.2 on 2021-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userstudent_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstudent',
            options={'ordering': ['user_id'], 'verbose_name': '用户-学生', 'verbose_name_plural': '用户-学生'},
        ),
        migrations.AlterModelOptions(
            name='userteacher',
            options={'ordering': ['user_id'], 'verbose_name': '用户-教师', 'verbose_name_plural': '用户-教师'},
        ),
        migrations.AddField(
            model_name='userstudent',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='userteacher',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学生编号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='学生姓名'),
        ),
    ]
