# Generated by Django 3.2 on 2021-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210415_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userteacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='userteacher',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
