# Generated by Django 3.2 on 2021-04-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210415_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='state',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0),
        ),
        migrations.AlterField(
            model_name='userteacher',
            name='name',
            field=models.TextField(max_length=20, unique=True, verbose_name='用户姓名'),
        ),
        migrations.AlterField(
            model_name='userteacher',
            name='state',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0),
        ),
        migrations.AlterModelTable(
            name='userteacher',
            table='UserTeacher',
        ),
    ]
