# Generated by Django 3.2 on 2021-04-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyCourse',
            new_name='Course',
        ),
    ]
