# Generated by Django 3.2 on 2021-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_mycourse_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='课程编号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teachers',
            field=models.TextField(max_length=200, verbose_name='任课教师'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='课程名字'),
        ),
    ]
