# Generated by Django 3.2 on 2021-04-16 02:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.TextField(primary_key=True, serialize=False, verbose_name='课程编号')),
                ('course_name', models.TextField(max_length=200, verbose_name='课程名字')),
                ('course_teachers', models.CharField(max_length=200, verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'CourseInfo',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=200, verbose_name='文件名称')),
                ('remarks', models.TextField(max_length=200, verbose_name='文件备注')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('uploader_id', models.IntegerField(verbose_name='上传者编号')),
                ('download_times', models.IntegerField(default=0, verbose_name='下载次数')),
                ('file_size', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='文件大小')),
                ('file_info', models.FileField(upload_to='upload/%Y%m%d')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.courseinfo')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'FileInfo',
            },
        ),
    ]
