# Generated by Django 3.2 on 2021-04-17 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=200, verbose_name='文件名称')),
                ('remarks', models.TextField(max_length=200, verbose_name='文件备注')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('uploader_id', models.TextField(max_length=20, verbose_name='上传者编号')),
                ('download_times', models.IntegerField(default=0, verbose_name='下载次数')),
                ('file_info', models.FileField(upload_to='upload/%Y%m%d')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.mycourse')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'FileInfo',
            },
        ),
    ]
