# Generated by Django 3.2 on 2021-04-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='course_name',
            new_name='name',
        ),
    ]
