# Generated by Django 3.2 on 2021-04-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_rename_course_name_courseinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_size',
        ),
    ]
