# Generated by Django 3.2 on 2021-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_remove_fileinfo_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='uploader_id',
            field=models.TextField(verbose_name='上传者编号'),
        ),
    ]
